language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=py36
cache:
- pip
script:
- pytest
deploy:
  provider: pypi
  user: htlemke
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: 1VxwH/VOGEm8+gY4sipabY1w/4nKjyxwyatKLknawApd9MsCUp7aiZ0RrvyKBHOwnvrQ/9vV9Zhday3GwHFBs14Bd8k9wAcjJQWodfp46Y2+FDyxTf/8vEDAY723PZ9Dc/duHztkWg00PabJVrKMmO4FK9lg6zxTCFBsozaBtDC2YqBUxbCYejMzPeRCm+bHUKlzOSWnw+R0/4Z64BTS+iQ0J9TEECPKM++02tmmAL6o6mszEZE0Zka4Rem/mh0PubMWBZhFxRv/eVHIftcpWR/FKjjXiMV0O/mm4anaxf969YdKMVwjJaHcyDU6plT6Z0R1u/Sv5N2V/1m6UXsCgZsTNnmk7RwmRCJd3+DA/5+ohilqpaNVqtmB0QAy9d4AjZJhlASvBRkHUIYE80m8VAocoPSwORi9a409S/BrCI/z8o7XJ/aIWseH7ohPoEIf3YPDxsR9JZ+S8n8u/nxLoddlr8QzOoguKcYRUd31WPKGF6P7RU/guDubKDIBzGVeiPTYC1ltaXU32hNMcd1HUHuRhg/kAWU+ckBzyM/oM8L7jkb/2XjomCQZIXQu6CqQ/EhRg10ri408NkvTo2LY3xh8brwAxeoe+8GK5GgxhKTZlblcXxNBzvExJc/FXgAdc0or2kF/fAi70XLMOnWxmje8nX1881IV7pUm63rUiiM=
